general {
    lock_cmd = pidof hyprlock || hyprlock       # comando para bloquear
    before_sleep_cmd = loginctl lock-session    # bloquea antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # asegura que el monitor encienda al volver
}

# --- COMENTA O ELIMINA LOS BLOQUES DE ABAJO ---

# Este bloque suele bajar el brillo (coméntalo si no lo quieres)
# listener {
#     timeout = 150
#     on-timeout = brightnessctl set 10%
#     on-resume = brightnessctl set 100%
# }

# ESTE ES EL QUE APAGA LA PANTALLA (Obligatorio comentar)
# listener {
#     timeout = 300                                 # 5 minutos
#     on-timeout = hyprctl dispatch dpms off        # <--- Apaga el monitor
#     on-resume = hyprctl dispatch dpms on          # <--- Enciende el monitor
# }

# ESTE ES EL QUE BLOQUEA LA SESIÓN (Opcional, coméntalo si no quieres que se bloquee)
# listener {
#     timeout = 600                                 # 10 minutos
#     on-timeout = loginctl lock-session            # <--- Bloquea la pantalla
# }
